apiVersion: "kubeflow.org/v1"
kind: "PyTorchJob"
metadata:
  name: "pytorch-dist-mnist-gloo"
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            steamer-service-type: system
            sidecar.istio.io/inject: "false"
        spec:
          containers:
            - name: pytorch
              image: harbor.tidu.cd/qujun/pytorch-dist-mnist-test:1.0
              imagePullPolicy: Always
              args: ["--backend", "gloo"]
              # Comment out the below resources to use the CPU.
              resources: 
    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            steamer-service-type: system
            sidecar.istio.io/inject: "false"
        spec:
          containers: 
            - name: pytorch
              image: harbor.tidu.cd/qujun/pytorch-dist-mnist-test:1.0
              imagePullPolicy: Always
              args: ["--backend", "gloo"]
              # Comment out the below resources to use the CPU.
              resources: 
